(function(){
'use strict';
const q=id=>document.getElementById(id);let selected=null,existing=null;
async function mediaCall(body){const{data}=await sb.auth.getSession();if(!data.session)throw new Error('Session expired');const r=await fetch(SB_URL+'/functions/v1/media-admin',{method:'POST',headers:{'Content-Type':'application/json',apikey:SB_KEY,Authorization:'Bearer '+data.session.access_token},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Media request failed');return j}
function safeFileName(s){return String(s||'photo').replace(/[^a-zA-Z0-9._-]/g,'_')}
function storageName(url){try{const marker='/storage/v1/object/public/site-media/';const i=String(url||'').indexOf(marker);return i>=0?decodeURIComponent(String(url).slice(i+marker.length)):''}catch{return''}}
function numOrNull(v){const n=Number(v);return Number.isFinite(n)&&n>0?Math.round(n):null}
async function readOverride(){if(!selected)return null;const{data,error}=await sb.from('media_overrides').select('*').eq('page',selected.page).eq('selector',selected.selector).maybeSingle();if(error)throw error;return data||null}
async function openEditor(d,focus){selected=d;q('inlineImageEditor')?.classList.remove('hidden');q('selectedPhotoMode').textContent=d.mode==='background'?'Background Photo':'Image';q('selectedPhotoSelector').textContent=d.selector||'';q('selectedPhotoPreview').src=d.url||'assets/logo.svg';q('photoStatus').textContent='Loading photo settings…';try{existing=await readOverride()}catch(e){existing=null;q('photoStatus').textContent=e.message;return}q('photoUrl').value=existing?.url||d.url||'';q('photoWidth').value=existing?.width||'';q('photoHeight').value=existing?.height||'';q('photoWidth').placeholder=`Current ${d.width||'-'} px`;q('photoHeight').placeholder=`Current ${d.height||'-'} px`;q('photoFit').value=existing?.fit||'';q('photoPosition').value=existing?.position||'';q('photoStatus').textContent=existing?.is_deleted?'Photo is currently deleted/hidden.':'Photo selected. Changes apply to this exact photo location.';if(focus==='resize'){q('photoWidth').focus();q('photoWidth').select()}else if(focus==='edit'){q('photoUrl').focus();q('photoUrl').select()}}
async function saveOverride(patch,action='edit_photo'){if(!selected)return;const base=existing||{};const row={page:selected.page,selector:selected.selector,mode:selected.mode,url:Object.prototype.hasOwnProperty.call(patch,'url')?patch.url:(base.url??null),width:Object.prototype.hasOwnProperty.call(patch,'width')?patch.width:(base.width??null),height:Object.prototype.hasOwnProperty.call(patch,'height')?patch.height:(base.height??null),fit:Object.prototype.hasOwnProperty.call(patch,'fit')?patch.fit:(base.fit??null),position:Object.prototype.hasOwnProperty.call(patch,'position')?patch.position:(base.position??null),is_deleted:Object.prototype.hasOwnProperty.call(patch,'is_deleted')?patch.is_deleted:(base.is_deleted??false),updated_by:session.user.id,updated_at:new Date().toISOString()};const{data,error}=await sb.from('media_overrides').upsert(row,{onConflict:'page,selector'}).select().single();if(error)throw error;existing=data;await sb.from('admin_audit_log').insert({user_id:session.user.id,action,target:`${selected.page}:${selected.selector}`,details:{mode:selected.mode,url:row.url,width:row.width,height:row.height,fit:row.fit,position:row.position,is_deleted:row.is_deleted}})}
function resizeFile(file,w,h){return new Promise((resolve,reject)=>{if(!w&&!h)return resolve(file);const img=new Image();const u=URL.createObjectURL(file);img.onload=()=>{try{const tw=w||Math.max(1,Math.round(img.width*h/img.height)),th=h||Math.max(1,Math.round(img.height*w/img.width));const c=document.createElement('canvas');c.width=tw;c.height=th;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,tw,th);c.toBlob(b=>{URL.revokeObjectURL(u);b?resolve(b):reject(new Error('Resize failed'))},'image/webp',.92)}catch(e){URL.revokeObjectURL(u);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('Unable to read image'))};img.src=u})}
function to64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('Unable to read image file'));r.readAsDataURL(blob)})}
async function uploadSelected(){const f=q('photoFile').files?.[0];if(!f||!selected)return;q('photoStatus').textContent='Uploading and processing photo…';try{const w=numOrNull(q('photoWidth').value),h=numOrNull(q('photoHeight').value);const blob=await resizeFile(f,w,h);const oldName=storageName(existing?.url||selected.url);const name=oldName||`${Date.now()}-${safeFileName(f.name).replace(/\.(jpe?g|png|gif|webp)$/i,'')}.webp`;const result=await mediaCall({action:oldName?'replace':'upload',name,base64:await to64(blob),content_type:blob.type||f.type||'image/webp'});q('photoUrl').value=result.url;await saveOverride({url:result.url,width:w,height:h,fit:q('photoFit').value||null,position:q('photoPosition').value.trim()||null,is_deleted:false},oldName?'replace_photo':'upload_photo');q('photoStatus').textContent='Photo saved. Updating live preview…';q('photoFile').value='';setTimeout(loadPreview,250)}catch(e){q('photoStatus').textContent=e.message}}
async function applyEdit(){if(!selected)return;q('photoStatus').textContent='Applying photo edit…';try{await saveOverride({url:q('photoUrl').value.trim()||null,width:numOrNull(q('photoWidth').value),height:numOrNull(q('photoHeight').value),fit:q('photoFit').value||null,position:q('photoPosition').value.trim()||null,is_deleted:false},'edit_resize_photo');q('photoStatus').textContent='Photo updated.';setTimeout(loadPreview,250)}catch(e){q('photoStatus').textContent=e.message}}
async function deletePhoto(){if(!selected||!confirm('Delete this photo from this location? You can restore the original later.'))return;q('photoStatus').textContent='Deleting photo from page…';try{await saveOverride({is_deleted:true},'delete_photo');q('photoStatus').textContent='Photo removed from this location.';setTimeout(loadPreview,250)}catch(e){q('photoStatus').textContent=e.message}}
async function restoreOriginal(){if(!selected)return;q('photoStatus').textContent='Restoring original photo…';try{const{error}=await sb.from('media_overrides').delete().eq('page',selected.page).eq('selector',selected.selector);if(error)throw error;await sb.from('admin_audit_log').insert({user_id:session.user.id,action:'restore_original_photo',target:`${selected.page}:${selected.selector}`,details:{mode:selected.mode}});existing=null;q('photoStatus').textContent='Original photo restored.';setTimeout(loadPreview,250)}catch(e){q('photoStatus').textContent=e.message}}
async function quickAction(d){await openEditor(d,d.action==='resize'?'resize':d.action==='edit'?'edit':'');if(d.action==='replace')q('photoFile')?.click();else if(d.action==='delete')await deletePhoto();else if(d.action==='restore')await restoreOriginal()}
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.data?.type==='cms-media-select')openEditor(e.data);if(e.data?.type==='cms-media-action')quickAction(e.data)});
window.addEventListener('load',()=>{q('uploadPhoto')?.addEventListener('click',()=>q('photoFile')?.click());q('photoFile')?.addEventListener('change',uploadSelected);q('applyPhotoEdit')?.addEventListener('click',applyEdit);q('deletePhoto')?.addEventListener('click',deletePhoto);q('restorePhoto')?.addEventListener('click',restoreOriginal);q('openSheet')?.addEventListener('click',()=>window.open('https://docs.google.com/spreadsheets/d/1WuE1uhRfDrEaxQE6bS5C5LTuotNJ6zn_e1mBRqWCX6M/edit','_blank'));q('openCare')?.addEventListener('click',()=>window.open('customer-care.html','_blank'));q('pageSelect')?.addEventListener('change',()=>{selected=null;existing=null;q('inlineImageEditor')?.classList.add('hidden')});});
})();