const SB_URL='https://caxbhzgmwkhgdblotjvs.supabase.co';
const SB_KEY='sb_publishable_p6qXdrM6TF0ZW7Z5btj5jQ_-WP-ou6N';
const sb=supabase.createClient(SB_URL,SB_KEY);const $=id=>document.getElementById(id);let session=null,profile=null;
const CMS_BUILD='20260912.5';
init();
async function init(){const{data}=await sb.auth.getSession();session=data.session;if(!session){location.href='admin-login.html';return}const{data:p}=await sb.from('profiles').select('*').eq('id',session.user.id).single();profile=p;if(!profile?.is_active||profile.role!=='super_admin'){await sb.auth.signOut();location.href='admin-login.html';return}$('rolePill').textContent='Super Admin';$('userName').textContent=profile.display_name||'Super Admin';$('userEmail').textContent=session.user.email||'';bind();loadPreview();loadEdits();loadAudit();}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.tab,b));$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.href='admin-login.html'};$('openSite').onclick=()=>window.open('index.html','_blank');$('pageSelect').onchange=loadPreview;$('reloadPreview').onclick=loadPreview;$('typeSelect').onchange=()=>$('attrField').classList.toggle('hidden',$('typeSelect').value!=='attribute');$('saveEdit').onclick=saveEdit;$('refreshEdits').onclick=loadEdits;$('refreshAudit').onclick=loadAudit;const frame=$('previewFrame');frame?.addEventListener('load',ensureFreshPreviewCMS);window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='cms-select')return;const d=e.data;$('selectorInput').value=d.selector||'';$('typeSelect').value='html';$('attrField').classList.add('hidden');$('valueInput').value=d.html||'';$('editorStatus').textContent=`Selected ${d.tag}: ${d.selector}`});}
function openTab(name,button){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));$('tab-'+name)?.classList.add('active');button?.classList.add('active')}
function loadPreview(){const p=$('pageSelect').value,lang=$('langSelect').value==='all'?'en':$('langSelect').value;$('editorStatus').textContent='Loading live preview…';$('previewFrame').src=`${p}?cms-preview=1&lang=${encodeURIComponent(lang)}&adminBuild=${CMS_BUILD}&t=${Date.now()}`}
function ensureFreshPreviewCMS(){const f=$('previewFrame');try{const w=f.contentWindow,d=f.contentDocument;if(!w||!d)return;if(w.__DIWY_CMS_INLINE_PHOTOS__!==CMS_BUILD){const old=d.getElementById('adminFreshCms');old?.remove();const s=d.createElement('script');s.id='adminFreshCms';s.src=`cms.js?v=${CMS_BUILD}&t=${Date.now()}`;s.onload=()=>{$('editorStatus').textContent='Photo editor ready. Click any photo in the preview.'};s.onerror=()=>{$('editorStatus').textContent='Unable to load photo editor. Reload preview.'};(d.body||d.documentElement).appendChild(s)}else $('editorStatus').textContent='Photo editor ready. Click any photo in the preview.'}catch(e){$('editorStatus').textContent='Preview loaded. If photo controls are missing, press Reload Preview.'}}
async function saveEdit(){const page=$('pageSelect').value,selector=$('selectorInput').value.trim(),language=$('langSelect').value,edit_type=$('typeSelect').value,attribute_name=edit_type==='attribute'?$('attrInput').value.trim():null,value=$('valueInput').value;if(!selector){$('editorStatus').textContent='Select an element first.';return}$('editorStatus').textContent='Saving…';let q=sb.from('site_edits').select('id').eq('page',page).eq('selector',selector).eq('language',language).eq('edit_type',edit_type);if(attribute_name)q=q.eq('attribute_name',attribute_name);else q=q.is('attribute_name',null);const{data:existing}=await q.maybeSingle();let error;if(existing?.id)({error}=await sb.from('site_edits').update({value,attribute_name:attribute_name||null,is_enabled:true,updated_by:session.user.id,updated_at:new Date().toISOString()}).eq('id',existing.id));else({error}=await sb.from('site_edits').insert({page,selector,language,edit_type,attribute_name:attribute_name||null,value,is_enabled:true,updated_by:session.user.id}));if(error){$('editorStatus').textContent=error.message;return}await sb.from('admin_audit_log').insert({user_id:session.user.id,action:'edit_site',target:`${page}:${selector}`,details:{language,edit_type,attribute_name}});$('editorStatus').textContent='Saved. Reloading preview…';await loadEdits();setTimeout(loadPreview,300)}
async function loadEdits(){const{data,error}=await sb.from('site_edits').select('*').order('updated_at',{ascending:false}).limit(250);const body=$('editsBody');if(!body)return;body.innerHTML='';if(error){body.innerHTML=`<tr><td colspan="6">${escapeHtml(error.message)}</td></tr>`;return}(data||[]).forEach(e=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${e.page}</td><td><code>${escapeHtml(e.selector)}</code></td><td>${e.language}</td><td>${e.edit_type}</td><td>${new Date(e.updated_at).toLocaleString()}</td><td><button class="btn ghost">Disable</button></td>`;tr.querySelector('button').onclick=()=>disableEdit(e.id);body.appendChild(tr)})}
async function disableEdit(id){await sb.from('site_edits').update({is_enabled:false,updated_by:session.user.id,updated_at:new Date().toISOString()}).eq('id',id);loadEdits();loadPreview()}
async function loadAudit(){const{data,error}=await sb.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(200);const b=$('auditBody');if(!b)return;b.innerHTML='';if(error){b.innerHTML=`<tr><td colspan="4">${escapeHtml(error.message)}</td></tr>`;return}(data||[]).forEach(a=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${new Date(a.created_at).toLocaleString()}</td><td>${escapeHtml(a.action)}</td><td>${escapeHtml(a.target||'')}</td><td>${a.user_id||''}</td>`;b.appendChild(tr)})}
function escapeHtml(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
(function(){if(!document.querySelector('link[data-admin-gallery-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='admin-gallery.css?v=20260913.3';l.dataset.adminGalleryCss='1';document.head.appendChild(l)}if(!document.querySelector('script[data-admin-gallery]')){const s=document.createElement('script');s.src='admin-gallery.js?v=20260913.3';s.dataset.adminGallery='1';document.body.appendChild(s)}})();
