(function(){
'use strict';
const q=id=>document.getElementById(id);let editing=null;
const ready=()=>typeof sb!=='undefined'&&typeof session!=='undefined'&&session?.user;
async function waitInit(){for(let i=0;i<80&&!ready();i++)await new Promise(r=>setTimeout(r,100));if(!ready())return;bindGallery();await loadGalleryAdmin()}
function bindGallery(){q('newGalleryItem')?.addEventListener('click',()=>openEditor());q('cancelGalleryItem')?.addEventListener('click',closeEditor);q('saveGalleryItem')?.addEventListener('click',saveItem);q('galleryItemType')?.addEventListener('change',syncTypeFields);q('galleryPhotoFile')?.addEventListener('change',()=>previewFile('galleryPhotoFile','galleryMediaPreview'));q('galleryThumbFile')?.addEventListener('change',()=>previewFile('galleryThumbFile','galleryMediaPreview'));q('refreshGallery')?.addEventListener('click',loadGalleryAdmin);document.querySelector('[data-tab="gallery"]')?.addEventListener('click',loadGalleryAdmin)}
function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||'';return u.searchParams.get('v')||''}catch{return''}}
function autoThumb(url){const id=youtubeId(url);return id?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:'assets/logo.svg'}
function syncTypeFields(){const type=q('galleryItemType').value,isVideo=type==='youtube';q('galleryPhotoField')?.classList.toggle('hidden',isVideo);q('galleryYoutubeField')?.classList.toggle('hidden',!isVideo);q('galleryThumbField')?.classList.toggle('hidden',!isVideo);q('galleryRatioField')?.classList.toggle('hidden',isVideo);if(isVideo)q('galleryAspectRatio').value='16:9';const preview=q('galleryMediaPreview');if(preview&&!editing)preview.src='assets/logo.svg'}
function openEditor(item=null){editing=item;q('galleryEditor')?.classList.remove('hidden');q('galleryItemId').value=item?.id||'';q('galleryItemType').value=item?.item_type||'photo';q('galleryTitle').value=item?.title||'';q('galleryDescription').value=item?.description||'';q('galleryAspectRatio').value=item?.aspect_ratio||'1:1';q('galleryYoutubeUrl').value=item?.youtube_url||'';q('galleryMediaUrl').value=item?.media_url||'';q('galleryThumbUrl').value=item?.thumbnail_url||'';q('galleryPhotoFile').value='';q('galleryThumbFile').value='';q('galleryMediaPreview').src=item?.item_type==='youtube'?(item.thumbnail_url||autoThumb(item.youtube_url)):(item?.media_url||'assets/logo.svg');q('galleryAdminStatus').textContent=item?'Editing gallery item.':'Adding new gallery item.';syncTypeFields();q('galleryEditor')?.scrollIntoView({behavior:'smooth',block:'start'})}
function closeEditor(){editing=null;q('galleryEditor')?.classList.add('hidden');q('galleryItemId').value='';q('galleryPhotoFile').value='';q('galleryThumbFile').value='';q('galleryAdminStatus').textContent=''}
function previewFile(inputId,imgId){const f=q(inputId)?.files?.[0];if(!f)return;const u=URL.createObjectURL(f);q(imgId).src=u;q(imgId).onload=()=>URL.revokeObjectURL(u)}
function storageName(url){try{const marker='/storage/v1/object/public/site-media/';const i=String(url||'').indexOf(marker);return i>=0?decodeURIComponent(String(url).slice(i+marker.length)):''}catch{return''}}
async function mediaCall(body){const{data}=await sb.auth.getSession();if(!data.session)throw new Error('Session expired');const r=await fetch(SB_URL+'/functions/v1/media-admin',{method:'POST',headers:{'Content-Type':'application/json',apikey:SB_KEY,Authorization:'Bearer '+data.session.access_token},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Media request failed');return j}
function processImage(file,mode='photo'){return new Promise((resolve,reject)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{try{let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight,dw,dh;if(mode==='thumb'){const target=16/9,src=sw/sh;if(src>target){const nw=sh*target;sx=(sw-nw)/2;sw=nw}else{const nh=sw/target;sy=(sh-nh)/2;sh=nh}dw=1280;dh=720}else{const max=1800,scale=Math.min(1,max/Math.max(sw,sh));dw=Math.max(1,Math.round(sw*scale));dh=Math.max(1,Math.round(sh*scale))}const c=document.createElement('canvas');c.width=dw;c.height=dh;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,sx,sy,sw,sh,0,0,dw,dh);c.toBlob(b=>{URL.revokeObjectURL(u);b?resolve(b):reject(new Error('Unable to process image'))},'image/webp',.92)}catch(e){URL.revokeObjectURL(u);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('Unable to read image'))};img.src=u})}
function to64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('Unable to read file'));r.readAsDataURL(blob)})}
async function uploadImage(file,existingUrl,prefix,mode){if(!file)return existingUrl||null;const blob=await processImage(file,mode),old=storageName(existingUrl),base=(file.name||prefix).replace(/[^a-zA-Z0-9._-]/g,'_').replace(/\.(jpe?g|png|gif|webp)$/i,'');const name=old||`${prefix}-${Date.now()}-${base}.webp`;const out=await mediaCall({action:old?'replace':'upload',name,base64:await to64(blob),content_type:'image/webp'});return out.url}
async function saveItem(){const id=q('galleryItemId').value.trim(),item_type=q('galleryItemType').value,title=q('galleryTitle').value.trim(),description=q('galleryDescription').value.trim(),aspect_ratio=item_type==='youtube'?'16:9':q('galleryAspectRatio').value,youtube_url=item_type==='youtube'?q('galleryYoutubeUrl').value.trim():null;if(!title){q('galleryAdminStatus').textContent='Title is required.';return}if(item_type==='youtube'&&!youtubeId(youtube_url)){q('galleryAdminStatus').textContent='Enter a valid YouTube link.';return}q('saveGalleryItem').disabled=true;q('galleryAdminStatus').textContent='Uploading media and saving…';try{let media_url=item_type==='photo'?q('galleryMediaUrl').value||null:null,thumbnail_url=item_type==='youtube'?q('galleryThumbUrl').value||null:null;if(item_type==='photo'){media_url=await uploadImage(q('galleryPhotoFile').files?.[0],media_url,'gallery-photo','photo');if(!media_url)throw new Error('Choose a photo to upload.')}else thumbnail_url=await uploadImage(q('galleryThumbFile').files?.[0],thumbnail_url,'gallery-thumb','thumb');const row={item_type,media_url,thumbnail_url,youtube_url,title,description,aspect_ratio,is_active:editing?.is_active??true,updated_at:new Date().toISOString()};let error;if(id)({error}=await sb.from('gallery_items').update(row).eq('id',id));else({error}=await sb.from('gallery_items').insert({...row,created_by:session.user.id}));if(error)throw error;await sb.from('admin_audit_log').insert({user_id:session.user.id,action:id?'update_gallery_item':'create_gallery_item',target:id||title,details:{item_type,title,aspect_ratio,youtube_url}});q('galleryAdminStatus').textContent='Gallery item saved.';closeEditor();await loadGalleryAdmin()}catch(e){q('galleryAdminStatus').textContent=e.message||'Unable to save gallery item.'}finally{q('saveGalleryItem').disabled=false}}
async function loadGalleryAdmin(){const box=q('galleryAdminGrid');if(!box)return;box.innerHTML='<div class="status">Loading gallery…</div>';const{data,error}=await sb.from('gallery_items').select('*').order('created_at',{ascending:false});if(error){box.innerHTML=`<div class="status">${escapeHtml(error.message)}</div>`;return}box.innerHTML='';(data||[]).forEach(item=>{const thumb=item.item_type==='youtube'?(item.thumbnail_url||autoThumb(item.youtube_url)):(item.media_url||'assets/logo.svg'),card=document.createElement('article');card.className='admin-gallery-card';card.innerHTML=`<div class="admin-gallery-thumb"><img src="${escapeHtml(thumb)}" alt=""><span>${item.item_type==='youtube'?'YouTube · 16:9':`Photo · ${escapeHtml(item.aspect_ratio)}`}</span></div><div class="admin-gallery-copy"><h3>${escapeHtml(item.title||'Untitled')}</h3><p>${escapeHtml((item.description||'').slice(0,130))}</p><div class="row"><button class="btn ghost edit">Edit</button><button class="btn ghost toggle">${item.is_active?'Hide':'Show'}</button><button class="btn danger del">Delete</button></div></div>`;card.querySelector('img').onerror=e=>{e.currentTarget.onerror=null;e.currentTarget.src='assets/logo.svg'};card.querySelector('.edit').onclick=()=>openEditor(item);card.querySelector('.toggle').onclick=()=>toggleItem(item);card.querySelector('.del').onclick=()=>deleteItem(item);box.appendChild(card)});if(!data?.length)box.innerHTML='<div class="status">No gallery items yet.</div>'}
async function toggleItem(item){const{error}=await sb.from('gallery_items').update({is_active:!item.is_active,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)return alert(error.message);await sb.from('admin_audit_log').insert({user_id:session.user.id,action:item.is_active?'hide_gallery_item':'show_gallery_item',target:item.id,details:{title:item.title}});loadGalleryAdmin()}
async function deleteItem(item){if(!confirm(`Delete “${item.title||'this item'}” from Gallery?`))return;for(const url of [item.media_url,item.thumbnail_url]){const name=storageName(url);if(name)try{await mediaCall({action:'delete',name})}catch{}}const{error}=await sb.from('gallery_items').delete().eq('id',item.id);if(error)return alert(error.message);await sb.from('admin_audit_log').insert({user_id:session.user.id,action:'delete_gallery_item',target:item.id,details:{title:item.title,item_type:item.item_type}});loadGalleryAdmin()}
window.addEventListener('load',waitInit);
})();