(function(){
'use strict';
const SB_URL='https://caxbhzgmwkhgdblotjvs.supabase.co';
const SB_KEY='sb_publishable_p6qXdrM6TF0ZW7Z5btj5jQ_-WP-ou6N';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function ratioClass(r){return 'ratio-'+String(r||'1:1').replace(':','-')}
function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||'';return u.searchParams.get('v')||''}catch{return''}}
function videoThumb(item){if(item.thumbnail_url)return item.thumbnail_url;const id=youtubeId(item.youtube_url);return id?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:'assets/logo.svg'}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function driftStyle(){const dx=(Math.random()*42-21).toFixed(1),dy=(Math.random()*48-24).toFixed(1),rot=(Math.random()*4-2).toFixed(2),dur=(9+Math.random()*9).toFixed(1),delay=(-Math.random()*8).toFixed(1),pulse=(1.008+Math.random()*.018).toFixed(3);return `--dx:${dx}px;--dy:${dy}px;--rot:${rot}deg;--dur:${dur}s;--delay:${delay}s;--pulse:${pulse}`}
function photoCard(item){const title=esc(item.title||'Photo'),desc=esc(item.description||'');return `<article class="gallery-float" style="${driftStyle()}"><div class="gallery-media-card"><button class="gallery-photo-button" type="button" data-gallery-photo="${item.id}" aria-label="Open ${title}"><div class="gallery-media ${ratioClass(item.aspect_ratio)}"><img src="${esc(item.media_url)}" alt="${title}" loading="lazy"><span class="gallery-type-badge">Photo</span></div><div class="gallery-caption"><h3>${title}</h3>${desc?`<p>${desc}</p>`:''}</div></button></div></article>`}
function videoCard(item){const title=esc(item.title||'Video'),desc=esc(item.description||''),thumb=esc(videoThumb(item)),url=esc(item.youtube_url||'#');return `<article class="gallery-float" style="${driftStyle()}"><div class="gallery-media-card gallery-video"><a class="gallery-video-link" href="${url}" target="_blank" rel="noopener" aria-label="Open ${title} on YouTube"><div class="gallery-media ratio-16-9"><img src="${thumb}" alt="${title}" loading="lazy"><span class="gallery-type-badge">YouTube</span><span class="gallery-play" aria-hidden="true"></span></div><div class="gallery-caption"><h3>${title}</h3>${desc?`<p>${desc}</p>`:''}</div></a></div></article>`}
let items=[];
async function load(){const stage=$('galleryStage');if(!stage)return;stage.innerHTML='<div class="gallery-loading">Loading gallery…</div>';try{const r=await fetch(`${SB_URL}/rest/v1/gallery_items?select=id,item_type,media_url,thumbnail_url,youtube_url,title,description,aspect_ratio,is_active,created_at&is_active=eq.true&order=created_at.desc`,{headers:{apikey:SB_KEY},cache:'no-store'});if(!r.ok)throw new Error('Gallery could not be loaded');items=shuffle(await r.json());if(!items.length){stage.innerHTML='<div class="gallery-empty">Gallery items will appear here.</div>';return}stage.innerHTML=items.map(x=>x.item_type==='youtube'?videoCard(x):photoCard(x)).join('');stage.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.onerror=null;img.src='assets/logo.svg'},{once:true}));stage.querySelectorAll('[data-gallery-photo]').forEach(btn=>btn.addEventListener('click',()=>openPhoto(btn.dataset.galleryPhoto)))}catch(e){stage.innerHTML=`<div class="gallery-empty">${esc(e.message)}</div>`}}
function openPhoto(id){const x=items.find(i=>i.id===id);if(!x)return;$('galleryModalImage').src=x.media_url;$('galleryModalImage').alt=x.title||'Gallery photo';$('galleryModalTitle').textContent=x.title||'';$('galleryModalDescription').textContent=x.description||'';$('galleryModal').classList.add('open');$('galleryModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){$('galleryModal')?.classList.remove('open');$('galleryModal')?.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function bind(){$('galleryModalClose')?.addEventListener('click',closeModal);$('galleryModal')?.addEventListener('click',e=>{if(e.target===$('galleryModal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();