const menuButton=document.querySelector('.menu');
const nav=document.querySelector('.links');
if(menuButton&&nav){menuButton.addEventListener('click',()=>{nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',nav.classList.contains('open')?'true':'false')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}

const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}}));

/* Luxury hero slider */
(function(){const root=document.getElementById('heroSlider');if(!root)return;const slides=[...root.querySelectorAll('.hero-slide')],dots=[...root.querySelectorAll('.hero-dot')],prev=root.querySelector('.hero-prev'),next=root.querySelector('.hero-next');let active=0,timer;const show=i=>{active=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('is-active',n===active));dots.forEach((d,n)=>d.classList.toggle('is-active',n===active))};const restart=()=>{clearInterval(timer);timer=setInterval(()=>show(active+1),5600)};dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);restart()}));prev?.addEventListener('click',()=>{show(active-1);restart()});next?.addEventListener('click',()=>{show(active+1);restart()});root.addEventListener('mouseenter',()=>clearInterval(timer));root.addEventListener('mouseleave',restart);let sx=0;root.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});root.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>55){show(active+(dx<0?1:-1));restart()}},{passive:true});show(0);restart()})();

/* Reveal motion */
(function(){const els=[...document.querySelectorAll('.reveal')];if(!els.length)return;if(!('IntersectionObserver'in window)){els.forEach(el=>el.classList.add('is-visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -45px'});els.forEach(el=>io.observe(el))})();

/* Rotating Google branch review panels */
(function(){const root=document.getElementById('reviewSlider');if(!root)return;const slides=[...root.querySelectorAll('[data-review-slide]')];const controls=[...document.querySelectorAll('[data-review-target]')];if(!slides.length)return;let active=0,timer;const show=i=>{active=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('is-active',n===active));controls.forEach(c=>c.classList.toggle('is-active',Number(c.dataset.reviewTarget)===active))};const restart=()=>{clearInterval(timer);timer=setInterval(()=>show(active+1),6500)};controls.forEach(c=>c.addEventListener('click',()=>{show(Number(c.dataset.reviewTarget));restart()}));root.addEventListener('mouseenter',()=>clearInterval(timer));root.addEventListener('mouseleave',restart);show(0);restart()})();

/* Sri Lanka two-location overview map */
(function(){const el=document.getElementById('branchMap');if(!el||typeof L==='undefined')return;const map=L.map(el,{scrollWheelZoom:false,zoomControl:true,attributionControl:true}).setView([7.45,80.35],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const icon=L.divIcon({className:'',html:'<div class="diwy-pin"></div>',iconSize:[34,34],iconAnchor:[17,34],popupAnchor:[0,-30]});const places=[{name:'Diwyashakthi Wedamedura · Eppawala',town:'Eppawala',lat:8.1426,lng:80.4030,url:'https://maps.app.goo.gl/i4UTNHPgaVRHqiWU6'},{name:'Diwyashakthi Wedamedura · Homagama',town:'Homagama',lat:6.8440,lng:80.0032,url:'https://maps.app.goo.gl/jk5YtXjadKttFqFk8'}];const markers=places.map(p=>L.marker([p.lat,p.lng],{icon}).addTo(map).bindPopup(`<div class="map-popup"><h4>${p.name}</h4><p>${p.town}, Sri Lanka</p><a href="${p.url}" target="_blank" rel="noopener">Get Directions</a></div>`));const group=L.featureGroup(markers);map.fitBounds(group.getBounds().pad(.8),{maxZoom:8});setTimeout(()=>map.invalidateSize(),250)})();

/* Contact form -> WhatsApp */
const contactForm=document.getElementById('contactForm');
if(contactForm){contactForm.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('name')?.value.trim()||'';const phone=document.getElementById('phone')?.value.trim()||'';const message=document.getElementById('message')?.value.trim()||'';const text=`Hello Diwyashakthi Wedamedura,\n\nName: ${name}\nPhone: ${phone||'-'}\n\n${message}`;window.open(`https://wa.me/94701424160?text=${encodeURIComponent(text)}`,'_blank','noopener')})}

/* Services disease browser */
const diseaseCatalog={
 vatha:{label:'වාත',title:'වාත රෝග',items:[
  {no:'01',name:'ස්නායු රෝග'},{no:'02',name:'හන්දි කැක්කුම'},{no:'03',name:'කොන්දේ කැක්කුම'},{no:'04',name:'වෙව්ලීම'},{no:'05',name:'සීතලට අකමැති වීම'},{no:'06',name:'ශරීරය කෙට්ටු වීම'},{no:'07',name:'ශරීරය රත් කට පහත වීම'},{no:'08',name:'මල බද්ධය'},{no:'09',name:'වාත කැක්කුම'},{no:'10',name:'අප්‍රාණිකත්වය / ක්ලාන්තික මෝචනය'},{no:'11',name:'නහර ගැට ගැසීම'},{no:'12',name:'සන්ධි ඉදිමීම හා කැක්කුම'},{no:'13',name:'හෘදයාබාධ'},{no:'14',name:'අංගභාගය'},{no:'15',name:'සයටිකා (ගුදසි)'},{no:'16',name:'විලුඹ කැක්කුම'},{no:'17',name:'අත - පය ඇඟිලි හිරි වැටීම'},{no:'18',name:'කොලෙස්ටරෝල්'},{no:'19',name:'අක්මාවේ රෝග'},{no:'20',name:'අඩි රැසර පීඩනය'}]},
 pitha:{label:'පිත',title:'පිත රෝග',items:[
  {no:'21',name:'දිව පැලීම, කකුල් පැලීම'},{no:'22',name:'අමිල පිත්තය (ගැස්ට්‍රයිටීස්)'},{no:'23',name:'රක්ත පිත්තය (ලේ උෂ්ණ වීම)'},{no:'24',name:'කුරුලෑ ගෙඩි'},{no:'25',name:'රක්ත ප්‍රදරය (ආර්ථව චක්‍රයේ ගැටලු)'},{no:'26',name:'ස්වේත ප්‍රදරය (සුදු යාම)'},{no:'27',name:'ශරීර දාහය (ඇඟ දැවිල්ල)'},{no:'28',name:'වර්ණ රෝග / දද / කුෂ්ඨ'},{no:'29',name:'අර්ශස්'},{no:'30',name:'ගර්භාශයේ ගෙඩි, පැලෝපීය නාල වල ගෙඩි'},{no:'31',name:'අරුචිය, උද්ගාරය (බඩ පිපුම)'},{no:'32',name:'ආහාර අසාත්මිකතාව'},{no:'33',name:'තයිරොක්සින්'},{no:'34',name:'මලබද්ධය'},{no:'35',name:'අග්නි මාන්දය (කුසගිනි නොමැතිකම)'},{no:'36',name:'තට්ටය ඇති වීම'},{no:'37',name:'අස්වාභාවිකව හිසකෙස් ගැලවී යාම'},{no:'38',name:'හිසකෙස් තඹ වීම'},{no:'39',name:'හිස්හොරි'},{no:'40',name:'හර්නියා'},{no:'41',name:'පුරුස්මී ග්‍රන්ථි ප්‍රදාහය'},{no:'42',name:'මුත්‍ර පුදරය'}]},
 kapha:{label:'කප',title:'කප (සෙම) රෝග',items:[
  {no:'43',name:'ඇදුම'},{no:'44',name:'හතිය'},{no:'45',name:'පපුවේ මහන්සිය'},{no:'46',name:'කිවිසුම් යෑම'},{no:'47',name:'උගුර, කණ කැසීම'},{no:'48',name:'හොටු දියර ගැලීම'},{no:'49',name:'ඉරුවාරදය (මිග්‍රේන්)'},{no:'50',name:'සයනොසයිටීස් (කූටක ප්‍රදාහය)'},{no:'51',name:'අලස බව'},{no:'52',name:'අග්නි මාන්දය (කසගිනි නොමැතිකම)'},{no:'53',name:'නිද්‍රාව (නිදිමත බව)'},{no:'54',name:'ශරීරය තරබාරු වීම'},{no:'55',name:'මුහුණ හිස බර බව'},{no:'56',name:'ඇස් යට කළු වීම'},{no:'57',name:'ගඳ සුවඳ නොදැනීම'}]}
};
function buildDiseaseDetail(categoryKey,item){const category=diseaseCatalog[categoryKey];return `<span class="detail-chip">${category.label}</span><h3>${item.name}</h3><p><strong>${item.name}</strong> සඳහා මෙම විස්තරය දැනට editable placeholder එකක් ලෙස සකස් කර ඇත. රෝගයේ හේතු, ලක්ෂණ, ආයුර්වේද ප්‍රවේශය, ආහාර උපදෙස් සහ follow-up guidance පසුව මෙහි වෙන වෙනම සංස්කරණය කළ හැක.</p><div class="detail-grid"><div class="detail-card"><h4>මූලික හැඳින්වීම</h4><p>${item.name} මෙම වෙබ් අඩවියේ <strong>${category.label}</strong> කාණ්ඩය යටතේ දක්වා ඇත. මෙහි නිවැරදි වෘත්තීය විස්තරය පසුව update කළ හැක.</p></div><div class="detail-card"><h4>ලක්ෂණ හා හේතු</h4><p>මෙම කොටසට සාමාන්‍ය ලක්ෂණ, ඉතිහාසය සහ අවධානය යොමු කළ යුතු කරුණු එකතු කළ හැක.</p></div><div class="detail-card"><h4>ආයුර්වේද ප්‍රවේශය</h4><p>මෙම කොටසට අදාළ වෛද්‍ය උපදෙස් සහ වෘත්තීයමය ප්‍රතිකාර තොරතුරු පසුව එක් කළ හැක.</p></div><div class="detail-card"><h4>ආහාර හා ජීවන රටාව</h4><p>අදාළ ආහාර, දෛනික චර්යා සහ follow-up උපදෙස් පසුව edit කළ හැක.</p></div></div>`}
function initDiseaseBrowser(){const doshaNav=document.getElementById('doshaNav'),diseaseList=document.getElementById('diseaseList'),diseaseDetail=document.getElementById('diseaseDetail'),activeCategoryTitle=document.getElementById('activeCategoryTitle');if(!doshaNav||!diseaseList||!diseaseDetail||!activeCategoryTitle)return;let activeCategory='vatha',activeIndex=0;const render=()=>{doshaNav.innerHTML='';Object.keys(diseaseCatalog).forEach(key=>{const b=document.createElement('button');b.type='button';b.className=`dosha-tab ${activeCategory===key?'active':''}`;b.textContent=diseaseCatalog[key].title;b.addEventListener('click',()=>{activeCategory=key;activeIndex=0;render()});doshaNav.appendChild(b)});const group=diseaseCatalog[activeCategory];activeCategoryTitle.textContent=group.title;diseaseList.innerHTML='';group.items.forEach((item,index)=>{const b=document.createElement('button');b.type='button';b.className=`disease-item ${activeIndex===index?'active':''}`;b.innerHTML=`<span class="disease-number">${item.no}</span><span class="disease-name">${item.name}</span>`;b.addEventListener('click',()=>{activeIndex=index;render()});diseaseList.appendChild(b)});diseaseDetail.innerHTML=buildDiseaseDetail(activeCategory,group.items[activeIndex])};render()}
document.addEventListener('DOMContentLoaded',initDiseaseBrowser);
