const STORE_URL='https://caxbhzgmwkhgdblotjvs.supabase.co';
const STORE_KEY='sb_publishable_p6qXdrM6TF0ZW7Z5btj5jQ_-WP-ou6N';
const CART_KEY='diwyashakthi-cart-v1';
const storeLang=()=>localStorage.getItem('diwyashakthi-language')||document.documentElement.lang||'en';
const L={
 en:{eyebrow:'Ayurveda Products',title:'Traditional products, easy ordering.',intro:'Choose your products, add them to the cart, enter your delivery details and confirm your order through WhatsApp.',shop:'Shop',available:'Available Products',cart:'Cart',yourCart:'Your Cart',total:'Total',checkout:'Checkout',customerDetails:'Customer Details',requiredText:'All details below are required before confirming the order.',name:'Name',mobile:'Mobile Number',whatsappNo:'WhatsApp Number',address:'Address',orderTotal:'Order Total',confirm:'Confirm Order & Open WhatsApp',add:'Add to Cart',empty:'No products are available right now.',cartEmpty:'Your cart is empty.',loading:'Loading products…',orderSaving:'Saving your order…',orderReady:'Order saved. Opening WhatsApp…',orderFailed:'Unable to place order right now.'},
 si:{eyebrow:'ආයුර්වේද නිෂ්පාදන',title:'පාරම්පරික නිෂ්පාදන පහසුවෙන් ඇණවුම් කරන්න.',intro:'අවශ්‍ය නිෂ්පාදන තෝරා Cart එකට එකතු කර, ඔබගේ තොරතුරු ඇතුළත් කර WhatsApp හරහා ඇණවුම තහවුරු කරන්න.',shop:'වෙළඳසැල',available:'ලබාගත හැකි නිෂ්පාදන',cart:'Cart',yourCart:'ඔබගේ Cart එක',total:'එකතුව',checkout:'Checkout',customerDetails:'පාරිභෝගික තොරතුරු',requiredText:'ඇණවුම තහවුරු කිරීමට පහත සියලු තොරතුරු අනිවාර්යයි.',name:'නම',mobile:'ජංගම දුරකථන අංකය',whatsappNo:'WhatsApp අංකය',address:'ලිපිනය',orderTotal:'ඇණවුම් එකතුව',confirm:'ඇණවුම තහවුරු කර WhatsApp විවෘත කරන්න',add:'Cart එකට එක් කරන්න',empty:'දැනට නිෂ්පාදන නොමැත.',cartEmpty:'ඔබගේ Cart එක හිස්.',loading:'නිෂ්පාදන ලබාගනිමින්…',orderSaving:'ඇණවුම සුරකිමින්…',orderReady:'ඇණවුම සුරකින ලදී. WhatsApp විවෘත කරමින්…',orderFailed:'දැනට ඇණවුම තැබිය නොහැක.'},
 ta:{eyebrow:'ஆயுர்வேத தயாரிப்புகள்',title:'பாரம்பரிய தயாரிப்புகளை எளிதாக ஆர்டர் செய்யுங்கள்.',intro:'தயாரிப்புகளைத் தேர்ந்தெடுத்து Cart-இல் சேர்த்து, உங்கள் விவரங்களை நிரப்பி WhatsApp மூலம் ஆர்டரை உறுதிப்படுத்துங்கள்.',shop:'கடை',available:'கிடைக்கும் தயாரிப்புகள்',cart:'Cart',yourCart:'உங்கள் Cart',total:'மொத்தம்',checkout:'Checkout',customerDetails:'வாடிக்கையாளர் விவரங்கள்',requiredText:'ஆர்டரை உறுதிப்படுத்த கீழுள்ள அனைத்து விவரங்களும் அவசியம்.',name:'பெயர்',mobile:'மொபைல் எண்',whatsappNo:'WhatsApp எண்',address:'முகவரி',orderTotal:'ஆர்டர் மொத்தம்',confirm:'ஆர்டரை உறுதிப்படுத்து & WhatsApp திற',add:'Cart-இல் சேர்க்க',empty:'தற்போது தயாரிப்புகள் இல்லை.',cartEmpty:'உங்கள் Cart காலியாக உள்ளது.',loading:'தயாரிப்புகள் ஏற்றப்படுகின்றன…',orderSaving:'உங்கள் ஆர்டர் சேமிக்கப்படுகிறது…',orderReady:'ஆர்டர் சேமிக்கப்பட்டது. WhatsApp திறக்கப்படுகிறது…',orderFailed:'இப்போது ஆர்டர் செய்ய முடியவில்லை.'}
};
const t=k=>(L[storeLang()]||L.en)[k]||L.en[k]||k;
let products=[];let cart=readCart();const $=id=>document.getElementById(id);
function money(n){return `LKR ${Number(n||0).toFixed(2)}`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function productImage(p){return p?.image_url||'assets/logo.svg'}
function readCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCartCounts();renderCart()}
function renderCartCounts(){const n=cart.reduce((s,x)=>s+x.quantity,0);if($('cartCount'))$('cartCount').textContent=n;if($('cartCount2'))$('cartCount2').textContent=n}
function cartTotal(){return cart.reduce((s,x)=>{const p=products.find(p=>p.id===x.product_id);return s+(p?Number(p.price)*x.quantity:0)},0)}
function translateUi(){document.querySelectorAll('[data-store-i18n]').forEach(el=>el.textContent=t(el.dataset.storeI18n));renderProducts();renderCart()}
async function loadProducts(){if(!$('productGrid'))return;$('productStatus').textContent=t('loading');try{const r=await fetch(`${STORE_URL}/rest/v1/products?select=id,name,description,price,image_url,is_active&is_active=eq.true&order=created_at.desc`,{headers:{apikey:STORE_KEY},cache:'no-store'});if(!r.ok)throw new Error('Failed');products=await r.json();cart=cart.filter(x=>products.some(p=>p.id===x.product_id));saveCart();renderProducts();$('productStatus').textContent=''}catch(e){$('productStatus').textContent=t('orderFailed')}}
function renderProducts(){const grid=$('productGrid');if(!grid)return;if(!products.length){grid.innerHTML=`<div class="empty-state">${esc(t('empty'))}</div>`;return}grid.innerHTML='';products.forEach(p=>{const card=document.createElement('article');card.className='product-card';card.innerHTML=`<div class="product-photo"><img src="${esc(productImage(p))}" alt="${esc(p.name)}" loading="lazy"></div><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><div class="product-price">${money(p.price)}</div><div class="product-actions"><input class="qty-input" type="number" min="1" max="50" value="1" aria-label="Quantity"><button class="btn gold add-btn" type="button">${esc(t('add'))}</button></div>`;const img=card.querySelector('.product-photo img');img.onerror=()=>{img.onerror=null;img.src='assets/logo.svg'};const qty=card.querySelector('.qty-input');card.querySelector('.add-btn').onclick=()=>addToCart(p.id,Number(qty.value)||1);grid.appendChild(card)})}
function addToCart(product_id,quantity=1){quantity=Math.max(1,Math.min(50,quantity));const found=cart.find(x=>x.product_id===product_id);if(found)found.quantity=Math.min(50,found.quantity+quantity);else cart.push({product_id,quantity});saveCart();openCart()}
function renderCart(){const box=$('cartItems');if(!box)return;cart=cart.filter(x=>products.some(p=>p.id===x.product_id));if(!cart.length){box.innerHTML=`<div class="empty-state">${esc(t('cartEmpty'))}</div>`}else{box.innerHTML='';cart.forEach(item=>{const p=products.find(p=>p.id===item.product_id),row=document.createElement('div');row.className='cart-item';row.innerHTML=`<div class="cart-product-photo"><img src="${esc(productImage(p))}" alt="${esc(p.name)}"></div><div class="cart-item-main"><h4>${esc(p.name)}</h4><small>${money(p.price)} × ${item.quantity}</small><div class="cart-qty"><button type="button" class="minus">−</button><strong>${item.quantity}</strong><button type="button" class="plus">+</button></div></div><div class="cart-item-side"><strong>${money(Number(p.price)*item.quantity)}</strong><br><button class="remove-item" type="button">Remove</button></div>`;const img=row.querySelector('.cart-product-photo img');img.onerror=()=>{img.onerror=null;img.src='assets/logo.svg'};row.querySelector('.minus').onclick=()=>changeQty(item.product_id,-1);row.querySelector('.plus').onclick=()=>changeQty(item.product_id,1);row.querySelector('.remove-item').onclick=()=>removeItem(item.product_id);box.appendChild(row)})}if($('cartTotal'))$('cartTotal').textContent=money(cartTotal());if($('checkoutTotal'))$('checkoutTotal').textContent=money(cartTotal());renderCartCounts()}
function changeQty(id,d){const x=cart.find(x=>x.product_id===id);if(!x)return;x.quantity+=d;if(x.quantity<=0)return removeItem(id);x.quantity=Math.min(50,x.quantity);saveCart()}
function removeItem(id){cart=cart.filter(x=>x.product_id!==id);saveCart()}
function openCart(){if(!$('cartDrawer'))return;$('cartDrawer').classList.add('open');$('cartBackdrop').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');renderCart()}
function closeCart(){$('cartDrawer')?.classList.remove('open');$('cartBackdrop')?.classList.remove('open');$('cartDrawer')?.setAttribute('aria-hidden','true')}
function openCheckout(){if(!cart.length)return;closeCart();$('checkoutTotal').textContent=money(cartTotal());$('checkoutModal').classList.add('open');$('checkoutModal').setAttribute('aria-hidden','false')}
function closeCheckout(){$('checkoutModal')?.classList.remove('open');$('checkoutModal')?.setAttribute('aria-hidden','true')}
async function submitOrder(e){e.preventDefault();if(!cart.length)return;const customer={name:$('customerName').value.trim(),mobile_number:$('customerMobile').value.trim(),whatsapp_number:$('customerWhatsapp').value.trim(),address:$('customerAddress').value.trim()};if(Object.values(customer).some(v=>!v)){$('checkoutStatus').textContent=t('requiredText');return}$('confirmOrder').disabled=true;$('checkoutStatus').textContent=t('orderSaving');try{const r=await fetch(`${STORE_URL}/functions/v1/place-order`,{method:'POST',headers:{'Content-Type':'application/json',apikey:STORE_KEY},body:JSON.stringify({customer,items:cart})});const j=await r.json();if(!r.ok)throw new Error(j.error||t('orderFailed'));localStorage.setItem('diwyashakthi-customer',JSON.stringify(customer));cart=[];saveCart();$('checkoutStatus').textContent=`${t('orderReady')} ${j.order?.order_number||''}`;setTimeout(()=>{window.location.href=j.whatsapp_url},450)}catch(err){$('checkoutStatus').textContent=err.message||t('orderFailed')}finally{$('confirmOrder').disabled=false}}
function restoreCustomer(){try{const c=JSON.parse(localStorage.getItem('diwyashakthi-customer')||'{}');if($('customerName'))$('customerName').value=c.name||'';if($('customerMobile'))$('customerMobile').value=c.mobile_number||'';if($('customerWhatsapp'))$('customerWhatsapp').value=c.whatsapp_number||'';if($('customerAddress'))$('customerAddress').value=c.address||''}catch{}}
function bindStore(){renderCartCounts();$('openCart')?.addEventListener('click',openCart);$('openCart2')?.addEventListener('click',openCart);$('closeCart')?.addEventListener('click',closeCart);$('cartBackdrop')?.addEventListener('click',closeCart);$('checkoutBtn')?.addEventListener('click',openCheckout);$('closeCheckout')?.addEventListener('click',closeCheckout);$('checkoutForm')?.addEventListener('submit',submitOrder);restoreCustomer();translateUi();loadProducts();window.addEventListener('diwy-language-changed',translateUi)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindStore);else bindStore();
